#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$DB_BACKEND_USER" ENCRYPTED PASSWORD '$DB_BACKEND_PASS';
  CREATE DATABASE "$DB_BACKEND_NAME" OWNER "$DB_BACKEND_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$DB_BACKEND_NAME" TO "$DB_BACKEND_USER";
EOSQL
